### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mxbode** [fox-it/citrix-netscaler-triage#3]
Hi,
tried to scan our netscaler image. On my ubuntu mashine installed dissect.target with pip and tried the command

> python3 iocitrix.py netscaler-node1.vmdk
> Traceback (most recent call last):
>   File "iocitrix.py", line 20, in <module>
>     from dissect.target import Target
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/__init__.py", line 1, in <module>
>     from dissect.target.target import Target
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/target.py", line 10, in <module>
>     from dissect.target import filesystem, loader, plugin, volume
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/filesystem.py", line 17, in <module>
>     from dissect.target.helpers import fsutil, hashutil
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/helpers/hashutil.py", line 7, in <module>
>     from dissect.target.plugins.filesystem.resolver import ResolverPlugin
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/plugins/filesystem/resolver.py", line 4, in <module>
>     from dissect.target.plugin import Plugin, internal
>   File "/home/user/.local/lib/python3.8/site-packages/dissect/target/plugin.py", line 35, in <module>
>    PluginDescriptor = dict[str, Any]
> TypeError: 'type' object is not subscriptable`

**Comment by Schamper** [comment]
Hi @mxbode! Dissect requires Python >= 3.9. Could you upgrade your Python version and try again?

**Comment by mxbode** [comment]
Thank you! Following steps worked for me:

`sudo apt install -y python3.9
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.9 get-pip.py
python3.9 -m pip install -r requirements.txt
`
