### ISSUE TITLE
Disk image created by dd is only 10mb

### ISSUE THREAD

**Issue by yunzheng** [fox-it/citrix-netscaler-triage#6]
the code: 

```shell
local ~ $ ssh nsroot@<YOUR-NETSCALER-IP> shell dd if=/dev/ada0 bs=10M | tail -c +7 | head -c -6 > ada0.img
```

does not work on CLI unless I delete the tail and head sections.  Then the file is only 10MB, I'm assuming because of the 10M in the line above.  There is not enough room on the Netscaler to hold this image so the command must be done through SSH as above.

_Originally posted by @jaymahannah in https://github.com/fox-it/citrix-netscaler-triage/issues/4#issuecomment-1689189785_

**Comment by yunzheng** [comment]
hi @jaymahannah, I moved your issue here.

The images should be bigger than 10 megabytes, bs=10M means blocksize of 10 megabyte but doesn't mean it's the limit.
Was there any error message to stderr when you used `head` and `tail`?

Can you provide the first few bytes of the dumped image on your local machine using:

```shell
local ~ $ hexdump -C ada0.img | head
```

And it would help if you can provide the output of the following commands on your NetScaler.

To show the disks and sizes:
```shell
root@ns# df -h
```

the command to show the mounts:

```shell
root@ns# mount
```

and to show the kernel version (you can redact the hostname if needed):

```shell
root@ns# uname -a
```

**Comment by jaymahannah** [comment]
The issue was that the SSH was being done directly into the Netscaler instead of on a local machine.  Running the script on a Linux machine solved the problem of the file size: mine were 20GB+ and 400MB+ respectively.  

Now I'm on to the issue of "Target not recognized as a Citrix Netscaler"

**Comment by yunzheng** [comment]
Alright, closing this issue
